### ISSUE TITLE
Add the seconds to the clock request

### ISSUE THREAD

**Issue by edubbwa** [lemnet/SimpleWeather#1]
Not an issue ... Just a request to add the seconds to the clock.

**Comment by lemnet** [comment]
Thank you for the request.

I've added the enhancement label.
I think it would use much more battery so i'll make it optional and to make this optional, first I have to make settings.

So, no my priority, but i'll consider it.

**Comment by lemnet** [comment]
Added in this [commit](https://github.com/lemnet/SimpleWeather/commit/d559791fd0803883022077859875f080882be3d1)
You can tap on time to display it in minutes:seconds until another tap or the screen goes off.
